# name: pkgdown.yaml
# version: 0.1.0
# Description: Triggers the core pkgdown deployment and cleanup workflows. Based on https://raw.githubusercontent.com/Gilead-BioStats/gsm.utils/refs/heads/actions-v1/workflow_templates/pkgdown-all.yaml v0.4.1
name: pkgdown-all
on:
  push:
    branches: [main, dev]
  pull_request:
    types: [opened, synchronize, reopened, closed]
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      mode:
        description: "Mode to run: deploy or cleanup"
        required: true
        default: 'deploy'
        type: choice
        options:
          - deploy
          - cleanup
      pr-number:
        description: "Pull request number. Leave blank to deploy to a branch."
        type: string
      pkgdown-dev-mode:
        description: "Whether pkgdown should operate in dev mode."
        type: boolean
        default: false
permissions:
  contents: write
  pull-requests: write
jobs:
  call-pkgdown-core:
    uses: Gilead-BioStats/gsm.utils/.github/workflows/pkgdown-core.yaml@actions-v1
    with:
      mode: ${{ inputs.mode }}
      pr-number: ${{ inputs.pr-number }}
      pkgdown-dev-mode: ${{ inputs.pkgdown-dev-mode == true || github.event_name != 'release' && github.event_name != 'workflow_dispatch' }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
      app-id: ${{ secrets.PKGDOWN_APP_ID }}
      app-private-key: ${{ secrets.PKGDOWN_APP_PRIVATE_KEY }}
