# name: qcthat.yaml
# version: 0.1.0
# Description: Generate qcthat quality control reports for pull requests and releases and manage user acceptance testing.
on:
  pull_request:
    types: [opened, edited, reopened, synchronize, milestoned]
  release:
    types: [released]
  issues:
    types: [closed]
  workflow_dispatch:
    inputs:
      pr-number:
        description: PR number to which reports should be added (leave blank for none).
      milestone:
        description: Milestone name to use to target the milestone report (leave blank for none).
      tag:
        description: Release tag to which the report should be attached (leave blank for none).
      qcthat-ref:
        description: A specific qcthat GitHub reference, such as a tag ("@v1.0.0"), branch ("@dev"), commit ("@480c247"), or pull request number ("#312") to use for reports and UAT management. Defaults to the latest release, "@*release".
      issue-number:
        description: The closed issue number to process to update user acceptance testing information.

name: qcthat

permissions:
  # read: Required for generating reports and updating UAT status.
  # write: Required for initiating the UAT process.
  issues: write
  # read: Required for updating UAT status.
  # write: Required for adding reports to pull requests.
  pull-requests: write
  # write: Required for attaching reports to releases.
  contents: write
  # write: Required for updating UAT status.
  actions: write

jobs:
  qcthat:
    if: >-
      (github.event_name == 'issues' && contains(github.event.issue.labels.*.name, 'qcthat-uat')) ||
      github.event_name != 'issues'
    uses: Gilead-BioStats/qcthat/.github/workflows/qcthat-core.yaml@actions
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
    with:
      # Configuration variables for controlling workflow behavior
      manage-uat: true
      generate-pr-report: true
      generate-completed-report: true
      generate-milestone-report: true
      generate-release-report: true
      fail-for-test-failures: true
      fail-for-missing-tests: true
      # Event context passed through to the core workflow
      has-uat-label: ${{ contains(github.event.issue.labels.*.name, 'qcthat-uat') }}
      pr-number: ${{ github.event.pull_request.number || inputs.pr-number || '' }}
      milestone: ${{ github.event.pull_request.milestone.title || inputs.milestone || '' }}
      tag: ${{ github.event.release.tag_name || inputs.tag || '' }}
      issue-number: ${{ github.event.issue.number || inputs.issue-number || '' }}
      qcthat-ref: ${{ inputs.qcthat-ref || '@*release' }}
